tinyquad:
  wheels_controller:
    type        : "diff_drive_controller/DiffDriveController"
    left_wheel  : 'LB_wheel_joint'
    right_wheel : 'RB_wheel_joint'
    publish_rate: 20.0               # this is what the real icube platform publishes (default: 50)
    # These covariances are exactly what the real icube platform publishes
    pose_covariance_diagonal : [0.00001, 0.00001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.1, 0.1, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    # pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.003]
    # twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.003]
    enable_odom_tf: true

    # Wheel separation and diameter. These are both optional.
    # diff_drive_controller will attempt to read either one or both from the
    # URDF if not specified as a parameter
    wheel_separation : 0.2
    wheel_radius : 0.1

    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0 # default: 1.0
    wheel_radius_multiplier    : 1.0 # default: 1.0

    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 0.5
    # velocity_rolling_window_size: 1

    # frame_ids (same as real icube platform)
    base_frame_id: base_link # default: base_link
    odom_frame_id: odom           # default: odom

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 1.5  # m/s; move_base max_vel_x: 0.8
        has_acceleration_limits: true
        max_acceleration       : 1.0  # m/s^2; move_base acc_lim_x: 1.5
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 1.5  # rad/s; move_base max_rot_vel: 1.0
        has_acceleration_limits: true
        max_acceleration       : 1.0  # rad/s^2; move_base acc_lim_th: 2.0

  # /gazebo_ros_control:
  #   pid_gains:
  #     left_wheel_joint:
  #         p: 10.0
  #         i: 0.02
  #         d: 0.01
  #     right_wheel_joint:
  #         p: 10.0
  #         i: 0.02
  #         d: 0.01