tinyquad:
  wheels_controller:
    type        : "diff_drive_controller/DiffDriveController"
    left_wheel  : 'LB_wheel_joint'
    right_wheel : 'RB_wheel_joint'
    publish_rate: 20.0
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.003]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.003]
    enable_odom_tf: true

    wheel_separation : 0.2
    wheel_radius : 0.1

    cmd_vel_timeout: 0.5

    base_frame_id: base_link
    odom_frame_id: odom

    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 1.5
        has_acceleration_limits: true
        max_acceleration       : 1.0
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 1.5
        has_acceleration_limits: true
        max_acceleration       : 1.0

  # /gazebo_ros_control:
  #   pid_gains:
  #     left_wheel_joint:
  #         p: 10.0
  #         i: 0.02
  #         d: 0.01
  #     right_wheel_joint:
  #         p: 10.0
  #         i: 0.02
  #         d: 0.01