tinyquad:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: LFS_J
    pid: {p: 80.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: LFU_J
    pid: {p: 80.0, i: 0.01, d: 10.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: LFL_J
    pid: {p: 80.0, i: 0.01, d: 10.0}

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: RFS_J
    pid: {p: 80.0, i: 0.01, d: 10.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: RFU_J
    pid: {p: 80.0, i: 0.01, d: 10.0}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: RFL_J
    pid: {p: 80.0, i: 0.01, d: 10.0}

  joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: LBS_J
    pid: {p: 80.0, i: 0.01, d: 10.0}
  joint8_position_controller:
    type: effort_controllers/JointPositionController
    joint: LBU_J
    pid: {p: 80.0, i: 0.01, d: 10.0}
  joint9_position_controller:
    type: effort_controllers/JointPositionController
    joint: LBL_J
    pid: {p: 80.0, i: 0.01, d: 10.0}

  joint10_position_controller:
    type: effort_controllers/JointPositionController
    joint: RBS_J
    pid: {p: 80.0, i: 0.01, d: 10.0}
  joint11_position_controller:
    type: effort_controllers/JointPositionController
    joint: RBU_J
    pid: {p: 80.0, i: 0.01, d: 10.0}
  joint12_position_controller:
    type: effort_controllers/JointPositionController
    joint: RBL_J
    pid: {p: 80.0, i: 0.01, d: 10.0}