# param to use points or size
use_points: true

body_corners:
  point_0_x: 2.0
  point_0_y: 1.0
  point_0_z: 0.0

  point_1_x: -2.0
  point_1_y: 1.0
  point_1_z: 0.0

  point_2_x: -2.0
  point_2_y: -1.0
  point_2_z: 0.0

  point_3_x: 2.0
  point_3_y: -1.0
  point_3_z: 0.0

# body size in meters
body_size:
  length: 0.5
  width: 0.25

    # position of points
    #    ________ 
    # 0 |        | 3
    #   |        |
    #   |        |
    #   |        |
    #   |        |
    # 1 |________| 2