body_corners:
  point_0_x: 2.0
  point_0_y: 1.0
  point_0_z: 0.2

  point_1_x: -2.0
  point_1_y: 1.0
  point_1_z: 0.2

  point_2_x: -2.0
  point_2_y: -1.0
  point_2_z: 0.2

  point_3_x: 2.0
  point_3_y: -1.0
  point_3_z: 0.2